import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { supabase } from '../../lib/supabase';
import { useToast } from '../../contexts/ToastContext';
import { AlertTriangle, Archive, CheckCircle2, Download, Flag, Megaphone, PauseCircle, PlayCircle, RefreshCw, Search, ShieldAlert, X } from 'lucide-react';

type SchoolStatus = 'new' | 'setup' | 'ready' | 'active' | 'inactive' | 'suspended' | 'archived';
interface SchoolUsage { id:string; name:string; address:string; operational_status:SchoolStatus; status_reason:string; created_at:string; status_changed_at:string|null; admins:number; instructors:number; students:number; sections:number; schedules:number; last_attendance:string|null; open_support:number; has_active_year:boolean }
interface Snapshot { schools:SchoolUsage[]; totals:{schools:number;active:number;attention:number;students:number;instructors:number}; notifications:{attempts:number;delivered:number;failed:number}; open_health_events:number; open_support:number }
interface Announcement { id:string;title:string;message:string;severity:string;audience:string;school_ids:string[];published_at:string|null;expires_at:string|null;created_at:string }
interface FeatureFlag { id:string;key:string;name:string;description:string;enabled_globally:boolean;school_ids:string[];updated_at:string }
interface HealthEvent { id:string;source:string;event_type:string;severity:string;school_id:string|null;message:string;details:Record<string,unknown>;resolved_at:string|null;created_at:string }
type Tab = 'schools'|'onboarding'|'usage'|'health'|'announcements'|'flags'|'data';

const EMPTY: Snapshot = { schools:[], totals:{schools:0,active:0,attention:0,students:0,instructors:0}, notifications:{attempts:0,delivered:0,failed:0}, open_health_events:0, open_support:0 };
const TABS: {key:Tab;label:string}[] = [{key:'schools',label:'School Control'},{key:'onboarding',label:'Onboarding'},{key:'usage',label:'Usage'},{key:'health',label:'System Health'},{key:'announcements',label:'Announcements'},{key:'flags',label:'Feature Flags'},{key:'data',label:'Data & Exports'}];
const STATUS_STYLE:Record<SchoolStatus,string>={new:'bg-sky-100 text-sky-700',setup:'bg-violet-100 text-violet-700',ready:'bg-cyan-100 text-cyan-700',active:'bg-emerald-100 text-emerald-700',inactive:'bg-slate-100 text-slate-600',suspended:'bg-rose-100 text-rose-700',archived:'bg-amber-100 text-amber-700'};

export default function PlatformOperationsPage(){
  const {showToast}=useToast(); const [tab,setTab]=useState<Tab>('schools'); const [snapshot,setSnapshot]=useState<Snapshot>(EMPTY); const [loading,setLoading]=useState(true); const [query,setQuery]=useState('');
  const [selected,setSelected]=useState<SchoolUsage|null>(null); const [announcements,setAnnouncements]=useState<Announcement[]>([]); const [flags,setFlags]=useState<FeatureFlag[]>([]); const [health,setHealth]=useState<HealthEvent[]>([]);
  const [statusForm,setStatusForm]=useState<{status:SchoolStatus;reason:string}|null>(null); const [announcementForm,setAnnouncementForm]=useState({title:'',message:'',severity:'info',audience:'all'}); const [flagForm,setFlagForm]=useState({key:'',name:'',description:''});
  const load=useCallback(async()=>{setLoading(true);const [snap,ann,flg,events]=await Promise.all([supabase.rpc('get_platform_operations_snapshot'),supabase.from('platform_announcements').select('*').order('created_at',{ascending:false}),supabase.from('platform_feature_flags').select('*').order('name'),supabase.from('platform_health_events').select('*').order('created_at',{ascending:false}).limit(100)]);if(snap.error){showToast(snap.error.message,'error');}else setSnapshot((snap.data as Snapshot)??EMPTY);setAnnouncements((ann.data as Announcement[])??[]);setFlags((flg.data as FeatureFlag[])??[]);setHealth((events.data as HealthEvent[])??[]);setLoading(false)},[showToast]);
  useEffect(()=>{void load()},[load]);
  const schools=useMemo(()=>snapshot.schools.filter(s=>`${s.name} ${s.address} ${s.operational_status}`.toLowerCase().includes(query.toLowerCase())),[snapshot.schools,query]);
  const onboarding=(s:SchoolUsage)=>[{label:'School created',done:true},{label:'School administrator assigned',done:s.admins>0},{label:'Active academic year',done:s.has_active_year},{label:'Teachers added',done:s.instructors>0},{label:'Sections configured',done:s.sections>0},{label:'Schedules configured',done:s.schedules>0},{label:'First attendance recorded',done:!!s.last_attendance}];
  async function changeStatus(e:FormEvent){e.preventDefault();if(!selected||!statusForm)return;const {error}=await supabase.rpc('set_school_operational_status',{p_school_id:selected.id,p_status:statusForm.status,p_reason:statusForm.reason});if(error){showToast(error.message,'error');return}showToast(`${selected.name} is now ${statusForm.status}.`);setStatusForm(null);setSelected(null);await load()}
  async function createAnnouncement(e:FormEvent){e.preventDefault();const {error}=await supabase.from('platform_announcements').insert({...announcementForm,published_at:new Date().toISOString()});if(error)showToast(error.message,'error');else{showToast('Announcement published.');setAnnouncementForm({title:'',message:'',severity:'info',audience:'all'});await load()}}
  async function createFlag(e:FormEvent){e.preventDefault();const key=flagForm.key.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_');const {error}=await supabase.from('platform_feature_flags').insert({...flagForm,key});if(error)showToast(error.message,'error');else{showToast('Feature flag created.');setFlagForm({key:'',name:'',description:''});await load()}}
  async function toggleFlag(flag:FeatureFlag){const {error}=await supabase.from('platform_feature_flags').update({enabled_globally:!flag.enabled_globally,updated_at:new Date().toISOString()}).eq('id',flag.id);if(error)showToast(error.message,'error');else await load()}
  async function resolveEvent(id:string){const {error}=await supabase.from('platform_health_events').update({resolved_at:new Date().toISOString()}).eq('id',id);if(error)showToast(error.message,'error');else await load()}
  function exportSchools(){const headers=['School','Status','Students','Instructors','Admins','Sections','Schedules','Last attendance','Open support'];const rows=snapshot.schools.map(s=>[s.name,s.operational_status,s.students,s.instructors,s.admins,s.sections,s.schedules,s.last_attendance??'',s.open_support]);const csv=[headers,...rows].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`classpulse-platform-usage-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
  if(loading)return <div className="flex justify-center py-16"><div className="h-9 w-9 animate-spin rounded-full border-b-2 border-primary"/></div>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold text-slate-900">Platform Operations</h2><p className="text-sm text-slate-500">Operate schools, capacity, communications, releases, and platform safety.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><RefreshCw size={15}/>Refresh</button></div>
    <div className="flex gap-2 overflow-x-auto pb-1">{TABS.map(t=><button key={t.key} onClick={()=>setTab(t.key)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-sm font-semibold ${tab===t.key?'bg-primary text-white':'bg-white text-slate-600 border border-slate-200'}`}>{t.label}</button>)}</div>
    {(tab==='schools'||tab==='onboarding'||tab==='usage')&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Schools" value={snapshot.totals.schools}/><Metric label="Active" value={snapshot.totals.active}/><Metric label="Need attention" value={snapshot.totals.attention}/><Metric label="Students" value={snapshot.totals.students}/><Metric label="Instructors" value={snapshot.totals.instructors}/></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2"><Search size={15} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search schools..." className="w-full bg-transparent text-sm outline-none"/></div></>}
    {tab==='schools'&&<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">School</th><th>Status</th><th>Students</th><th>Teachers</th><th>Last attendance</th><th></th></tr></thead><tbody className="divide-y divide-slate-100">{schools.map(s=><tr key={s.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-semibold text-slate-800">{s.name}<div className="text-xs font-normal text-slate-400">{s.address}</div></td><td><Badge status={s.operational_status}/></td><td>{s.students.toLocaleString()}</td><td>{s.instructors}</td><td>{s.last_attendance?new Date(s.last_attendance).toLocaleString():'Never'}</td><td className="pr-4 text-right"><button onClick={()=>setSelected(s)} className="rounded-lg bg-slate-100 px-3 py-1.5 font-semibold text-primary">Manage</button></td></tr>)}</tbody></table></div>}
    {tab==='onboarding'&&<div className="grid gap-4 lg:grid-cols-2">{schools.map(s=>{const steps=onboarding(s),done=steps.filter(x=>x.done).length;return <div key={s.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-3 flex justify-between"><div><h3 className="font-bold text-slate-800">{s.name}</h3><p className="text-xs text-slate-400">{done}/{steps.length} setup checks complete</p></div><Badge status={s.operational_status}/></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500" style={{width:`${done/steps.length*100}%`}}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{steps.map(x=><div key={x.label} className={`flex items-center gap-2 text-xs ${x.done?'text-emerald-700':'text-slate-400'}`}>{x.done?<CheckCircle2 size={14}/>:<PauseCircle size={14}/>} {x.label}</div>)}</div></div>})}</div>}
    {tab==='usage'&&<UsageTable schools={schools}/>} 
    {tab==='health'&&<><div className="grid gap-3 sm:grid-cols-4"><Metric label="Notification attempts (24h)" value={snapshot.notifications.attempts}/><Metric label="Delivered" value={snapshot.notifications.delivered}/><Metric label="Failed" value={snapshot.notifications.failed}/><Metric label="Open health events" value={snapshot.open_health_events}/></div><div className="space-y-2">{health.length===0?<Empty text="No health events recorded."/>:health.map(h=><div key={h.id} className={`flex items-start gap-3 rounded-xl border p-4 ${h.resolved_at?'bg-slate-50 opacity-60':'bg-white'}`}><ShieldAlert className={h.severity==='critical'?'text-rose-500':'text-amber-500'} size={20}/><div className="flex-1"><div className="font-semibold text-slate-800">{h.message}</div><div className="text-xs text-slate-400">{h.source} · {h.event_type} · {new Date(h.created_at).toLocaleString()}</div></div>{!h.resolved_at&&<button onClick={()=>void resolveEvent(h.id)} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">Resolve</button>}</div>)}</div></>}
    {tab==='announcements'&&<div className="grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={createAnnouncement} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Publish announcement</h3><input required placeholder="Title" value={announcementForm.title} onChange={e=>setAnnouncementForm({...announcementForm,title:e.target.value})} className="w-full rounded-xl border p-2.5 text-sm"/><textarea required placeholder="Message" value={announcementForm.message} onChange={e=>setAnnouncementForm({...announcementForm,message:e.target.value})} className="h-28 w-full rounded-xl border p-2.5 text-sm"/><div className="grid grid-cols-2 gap-2"><select value={announcementForm.severity} onChange={e=>setAnnouncementForm({...announcementForm,severity:e.target.value})} className="rounded-xl border p-2.5 text-sm"><option>info</option><option>maintenance</option><option>warning</option><option>critical</option><option>release</option></select><select value={announcementForm.audience} onChange={e=>setAnnouncementForm({...announcementForm,audience:e.target.value})} className="rounded-xl border p-2.5 text-sm"><option value="all">Everyone</option><option value="school_admins">School admins</option><option value="instructors">Instructors</option></select></div><button className="w-full rounded-xl bg-primary py-2.5 font-semibold text-white"><Megaphone size={15} className="mr-2 inline"/>Publish</button></form><div className="space-y-3">{announcements.map(a=><div key={a.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between"><h3 className="font-bold text-slate-800">{a.title}</h3><span className="text-xs uppercase text-slate-400">{a.severity}</span></div><p className="mt-2 text-sm text-slate-600">{a.message}</p><p className="mt-2 text-xs text-slate-400">{a.audience} · {a.published_at?'Published':'Draft'}</p></div>)}</div></div>}
    {tab==='flags'&&<div className="grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={createFlag} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Create release flag</h3><input required placeholder="Flag name" value={flagForm.name} onChange={e=>setFlagForm({...flagForm,name:e.target.value,key:e.target.value})} className="w-full rounded-xl border p-2.5 text-sm"/><input placeholder="Description" value={flagForm.description} onChange={e=>setFlagForm({...flagForm,description:e.target.value})} className="w-full rounded-xl border p-2.5 text-sm"/><button className="w-full rounded-xl bg-primary py-2.5 font-semibold text-white"><Flag size={15} className="mr-2 inline"/>Create flag</button></form><div className="space-y-3">{flags.map(f=><div key={f.id} className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex-1"><h3 className="font-bold text-slate-800">{f.name}</h3><code className="text-xs text-slate-400">{f.key}</code><p className="text-sm text-slate-500">{f.description}</p></div><button onClick={()=>void toggleFlag(f)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${f.enabled_globally?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{f.enabled_globally?'Enabled':'Disabled'}</button></div>)}</div></div>}
    {tab==='data'&&<div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6"><Download className="text-primary"/><h3 className="mt-3 font-bold text-slate-800">Platform usage export</h3><p className="mt-1 text-sm text-slate-500">Download school status and aggregate usage. Student-level personal data is excluded.</p><button onClick={exportSchools} className="mt-4 rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white">Download CSV</button></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><Archive className="text-amber-600"/><h3 className="mt-3 font-bold text-amber-900">Retention and recovery</h3><p className="mt-1 text-sm text-amber-700">Schools are archived instead of directly deleted. Database backup and point-in-time restore remain controlled through Supabase.</p></div></div>}
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h3 className="text-xl font-bold">{selected.name}</h3><p className="text-sm text-slate-500">{selected.address}</p></div><button onClick={()=>{setSelected(null);setStatusForm(null)}}><X/></button></div><div className="mt-5 grid grid-cols-3 gap-3"><Metric label="Students" value={selected.students}/><Metric label="Teachers" value={selected.instructors}/><Metric label="Open support" value={selected.open_support}/></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><span className="font-semibold">Operational status</span><Badge status={selected.operational_status}/></div>{selected.status_reason&&<p className="mt-2 text-sm text-slate-500">Last reason: {selected.status_reason}</p>}</div>{statusForm?<form onSubmit={changeStatus} className="mt-5 space-y-3"><select value={statusForm.status} onChange={e=>setStatusForm({...statusForm,status:e.target.value as SchoolStatus})} className="w-full rounded-xl border p-2.5">{Object.keys(STATUS_STYLE).map(s=><option key={s}>{s}</option>)}</select><textarea required minLength={3} placeholder="Reason for this change" value={statusForm.reason} onChange={e=>setStatusForm({...statusForm,reason:e.target.value})} className="w-full rounded-xl border p-2.5"/><button className="w-full rounded-xl bg-primary py-2.5 font-semibold text-white">Confirm audited status change</button></form>:<div className="mt-5 flex flex-wrap gap-2"><Action icon={<PlayCircle size={15}/>} label="Activate" onClick={()=>setStatusForm({status:'active',reason:''})}/><Action icon={<PauseCircle size={15}/>} label="Suspend" onClick={()=>setStatusForm({status:'suspended',reason:''})}/><Action icon={<Archive size={15}/>} label="Archive" onClick={()=>setStatusForm({status:'archived',reason:''})}/></div>}</div></div>}
  </div>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-2xl font-bold text-slate-900">{value.toLocaleString()}</div><div className="text-xs text-slate-500">{label}</div></div>}
function Badge({status}:{status:SchoolStatus}){return <span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${STATUS_STYLE[status]}`}>{status}</span>}
function Action({icon,label,onClick}:{icon:React.ReactNode;label:string;onClick:()=>void}){return <button onClick={onClick} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700">{icon}{label}</button>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-slate-300 p-12 text-center text-sm text-slate-400"><AlertTriangle className="mx-auto mb-2"/>{text}</div>}
function UsageTable({schools}:{schools:SchoolUsage[]}){return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">School</th><th>Students</th><th>Teachers</th><th>Sections</th><th>Schedules</th><th>Admins</th><th>Support</th></tr></thead><tbody className="divide-y divide-slate-100">{schools.map(s=><tr key={s.id}><td className="px-4 py-3 font-semibold">{s.name}</td><td>{s.students}</td><td>{s.instructors}</td><td>{s.sections}</td><td>{s.schedules}</td><td>{s.admins}</td><td>{s.open_support}</td></tr>)}</tbody></table></div>}
